import { TechStackItem, SchemaTable, RoadmapPhase } from '../types/blueprint';

export const TECH_STACK: TechStackItem[] = [
  {
    category: "Mobile Client (Frontend)",
    recommended: "Native Android (Kotlin + Jetpack Compose) OR Flutter",
    alternatives: ["React Native"],
    rationale: "For a privacy-first app handling 500 MB file streams and WebRTC media hardware acceleration, Native Android (Kotlin) provides unmatched memory safety (direct ByteBuffer manipulation), zero-JNI overhead for cryptographic libraries (libsignal/libsodium), and Android Keystore hardware-backed security (StrongBox). If cross-platform is mandatory for iOS parity, Flutter with flutter_webrtc and Rust FFI provides predictable 60-120 FPS performance without JS bridge serialization bottlenecks.",
    pros: [
      "Hardware-backed Android Keystore / KeyStore provider",
      "Native WebRTC C++ bindings with direct SurfaceView rendering",
      "Coroutines & Flow for backpressure-aware chunked file streaming",
      "WorkManager for guaranteed reliable 24h background database cleanup"
    ],
    cons: [
      "Requires separate iOS codebase (Swift/SwiftUI) if cross-platform is needed later",
      "Higher initial development effort than hybrid React Native"
    ],
    productionNotes: "Use Jetpack Compose for reactive, declarative modern UI. Integrate libsignal-client or libsodium via JNI for high-throughput cryptographic primitives. Use OkHttp 4.12+ with custom ChunkedTransferRequestBody for direct disk-to-socket streaming."
  },
  {
    category: "Signaling & Gateway (Backend)",
    recommended: "Golang (Go) or Node.js (TypeScript + Fastify) with WebSocket / gRPC",
    alternatives: ["Elixir / Phoenix", "Rust (Actix)"],
    rationale: "Go provides low-footprint goroutines capable of sustaining 250k+ concurrent open WebSocket connections per server instance. For rapid MVP iterations, Node.js with Fastify and uWebSockets.js provides exceptional I/O throughput. Signaling servers maintain zero knowledge of message payloads—only routing public keys, session tokens, and encrypted envelopes.",
    pros: [
      "Sub-millisecond connection handling for WebRTC SDP offer/answer/ICE exchange",
      "Minimal RAM footprint (under 30MB baseline per instance in Go)",
      "Native concurrency models ideal for pub/sub message dispatching",
      "Stateless architecture easily horizontally scaled behind AWS ALB or Google Cloud Armor"
    ],
    cons: [
      "State synchronization across multi-node clusters requires a distributed Redis cache"
    ],
    productionNotes: "Deploy as containerized services on Google Cloud Run or AWS ECS Fargate with sticky WebSocket sessions. Implement Redis 7+ Sentinel/Cluster for real-time pub/sub routing between server replicas."
  },
  {
    category: "Real-time Media & WebRTC Infrastructure",
    recommended: "P2P WebRTC with COTURN (STUN/TURN) & LiveKit SFU fallback",
    alternatives: ["Jitsi Meet", "Janus WebRTC Server"],
    rationale: "1-on-1 audio and video calls operate directly Peer-to-Peer (P2P) using WebSockets for SDP signaling and DTLS-SRTP for peer media encryption. For restrictive NAT/firewall environments (~15-20% of mobile users), self-hosted COTURN instances deployed on geographically distributed nodes act as TURN relays without access to decrypted streams.",
    pros: [
      "True end-to-end encryption via WebRTC DTLS 1.3 and SRTP (AES-GCM-256)",
      "Zero server bandwidth cost for direct P2P connections",
      "Adaptive bitrate (ABR) with Opus audio (6-510 kbps) and VP8/VP9/AV1 video codecs",
      "Hardware H.264/VP8 encoder offloading on mobile devices"
    ],
    cons: [
      "TURN bandwidth can incur high cloud egress costs if not geo-optimized"
    ],
    productionNotes: "Deploy COTURN on Ubuntu VMs across US, EU, and APAC with ephemeral TURN credentials (HMAC-SHA1 time-limited tokens generated by signaling backend)."
  },
  {
    category: "Object Storage & Large Files (500 MB)",
    recommended: "Amazon S3 or Google Cloud Storage (GCS) with Direct Presigned URLs",
    alternatives: ["Cloudflare R2 (Zero Egress)"],
    rationale: "Server zero-knowledge mandate requires that backend servers NEVER process or touch unencrypted file payloads. The mobile client slices the 500 MB file, encrypts chunks locally using AES-256-GCM, and uploads directly to S3/GCS using multi-part presigned URLs. Cloudflare R2 is an outstanding alternative that eliminates egress bandwidth fees entirely.",
    pros: [
      "Zero server proxy bottleneck: mobile uploads directly to cloud storage buckets",
      "Native S3 Multi-Part Upload API supports up to 10,000 chunks of 5MB-100MB",
      "Automated Bucket Lifecycle Rules for zero-maintenance 24-hour file expiration",
      "High parallel concurrency (up to 4-8 parallel chunk upload streams per client)"
    ],
    cons: [
      "Requires fine-grained CORS and IAM presigned signature management"
    ],
    productionNotes: "Configure AWS S3 Lifecycle Rule: `Expiration: DaysAfterInitiation: 1` and `AbortIncompleteMultipartUpload: DaysAfterInitiation: 1`. Configure CORS for `PUT` and `GET` requests with `ETag` exposed."
  },
  {
    category: "Database & Authentication",
    recommended: "Firebase Authentication (Google OAuth) + PostgreSQL (Supabase) + Room (Client)",
    alternatives: ["Firestore NoSQL", "CockroachDB"],
    rationale: "Firebase Auth handles frictionless, production-grade Google Sign-In with device verification and secure JWT issuance. PostgreSQL stores user profiles, public key bundles (Prekey bundles for X3DH), device registrations, and transient message queues. On the client, Android Jetpack Room (SQLite with SQLCipher) provides fast, structured, encrypted on-device caching.",
    pros: [
      "OAuth 2.0 / OIDC Google Sign-In with zero credential maintenance",
      "ACID relational guarantees for Prekey bundle inventory management",
      "SQLCipher provides transparent AES-256 at-rest database encryption on mobile",
      "PostgreSQL row-level TTL indexes or pg_cron for backend housekeeping"
    ],
    cons: [
      "Must ensure database never stores plaintext message bodies or attachment decryption keys"
    ],
    productionNotes: "Store only opaque encrypted blobs, initialization vectors (IV), HMAC tags, and public keys. Enforce Row-Level Security (RLS) policies."
  },
  {
    category: "Anti-Hacker & Security Hardening Specifications",
    recommended: "Signal Protocol + SSL/TLS Pinning + RootBeer Root Detection + R8 Obfuscation + Keystore SQLCipher",
    alternatives: ["Standard TLS (without pinning)", "ProGuard basic"],
    rationale: "Comprehensive defense-in-depth architecture: SSL/TLS certificate pinning with OkHttp CertificatePinner completely blocks Man-in-the-Middle (MitM) inspection; RootBeer detects compromised/jailbroken Android operating systems; R8 obfuscation strips debug symbols and encrypts sensitive class strings; and Android Keystore (StrongBox Keymaster) safeguards the 256-bit database encryption key used by SQLCipher for transparent on-disk encryption.",
    pros: [
      "Zero MitM vulnerability even under compromised network environments",
      "Immediate memory zeroization and self-termination on rooted devices",
      "R8/ProGuard makes reverse engineering and Frida hooking exponentially harder",
      "Hardware-backed StrongBox TEE protection for local database master keys",
      "Signal Double Ratchet protects messages, voice notes, files, and WebRTC calls"
    ],
    cons: [
      "Requires automated certificate rotation procedures before SSL cert expiry",
      "Root detection may prevent power users on custom ROMs from running the app"
    ],
    productionNotes: "Configure CertificatePinner with both primary and backup CA SHA-256 public key hashes. Enforce R8 full mode with `-repackageclasses` and symbol renaming."
  }
];

export const DATABASE_SCHEMAS: SchemaTable[] = [
  {
    name: "users (Privacy Enforced - Display Name Only)",
    description: "Registered user profiles authenticated via Google OAuth. STRICT IDENTITY RULE: Only Google Display Name is exposed to clients or in API responses. Raw Gmail (user@gmail.com) is never sent or displayed.",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "Internal system user UUID" },
      { name: "firebase_uid", type: "VARCHAR(128)", constraints: "UNIQUE NOT NULL", description: "Immutable Google / Firebase UID token subject" },
      { name: "google_id_hash", type: "VARCHAR(64)", constraints: "UNIQUE NOT NULL", description: "One-way HMAC-SHA256 salted hash of Google ID for account deduplication" },
      { name: "display_name", type: "VARCHAR(100)", constraints: "NOT NULL", description: "Google Account Display Name (Profile Name) - SOLE public identity" },
      { name: "avatar_url", type: "TEXT", constraints: "NULL", description: "Optional avatar URL from Google Profile" },
      { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Registration timestamp" },
      { name: "last_seen_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Presence timestamp" }
    ],
    sqlDdl: `-- PostgreSQL Backend Schema (Strict Zero-Gmail Exposure)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    firebase_uid VARCHAR(128) UNIQUE NOT NULL,
    google_id_hash VARCHAR(64) UNIQUE NOT NULL, -- Never exposes raw email
    display_name VARCHAR(100) NOT NULL, -- Sole public user identity
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_users_display ON users(display_name);`,
    roomEntity: `// Android Room Entity (Kotlin) - Zero Gmail Storage Guarantee
@Entity(tableName = "users")
data class UserEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "display_name") val displayName: String, // Google Profile Name ONLY
    @ColumnInfo(name = "avatar_url") val avatarUrl: String?,
    @ColumnInfo(name = "last_seen_at") val lastSeenAt: Long
    // Note: Raw email is strictly omitted from mobile Room schema and memory models
)`
  },
  {
    name: "user_phone_hashes (Zero-Knowledge Contact Sync)",
    description: "Blinded contact telephone hashes for Private Set Intersection (PSI) friend matching. Raw phone numbers are NEVER stored or transmitted.",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "Hash record ID" },
      { name: "user_id", type: "UUID", constraints: "REFERENCES users(id) ON DELETE CASCADE", description: "Owning user UUID" },
      { name: "phone_hash", type: "VARCHAR(64)", constraints: "NOT NULL", description: "HMAC-SHA256(E.164_Phone, AppPepper) blinded hash" },
      { name: "synced_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Sync timestamp" }
    ],
    sqlDdl: `-- Blinded Phone Hashes for Private Set Intersection (PSI)
CREATE TABLE user_phone_hashes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    phone_hash VARCHAR(64) NOT NULL, -- Blinded hash computed locally on client
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, phone_hash)
);
CREATE INDEX idx_phone_hash_lookup ON user_phone_hashes(phone_hash);`,
    roomEntity: `// Android Room Entity for Local Address Book Hash Cache
@Entity(tableName = "local_contact_hashes")
data class ContactHashEntity(
    @PrimaryKey val phoneHash: String, // HMAC-SHA256 calculated on-device
    @ColumnInfo(name = "local_contact_name") val localContactName: String,
    @ColumnInfo(name = "is_ttm_member") val isTtmMember: Boolean,
    @ColumnInfo(name = "matched_user_id") val matchedUserId: String?
)`
  },
  {
    name: "security_audit_events (Screenshot & Recording Alerts)",
    description: "Ephemeral security event telemetry for real-time screenshot and screen recording alert dispatching.",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "Audit event UUID" },
      { name: "chat_id", type: "UUID", constraints: "NOT NULL", description: "Active chat session ID" },
      { name: "reporter_user_id", type: "UUID", constraints: "REFERENCES users(id)", description: "Device reporting the event" },
      { name: "event_type", type: "VARCHAR(40)", constraints: "CHECK (event_type IN ('SCREENSHOT_DETECTED', 'SCREEN_RECORDING_DETECTED'))", description: "Alert classification" },
      { name: "evidence_meta", type: "TEXT", constraints: "NOT NULL", description: "API 34 ScreenCaptureCallback or DisplayManager virtual flag" },
      { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Detection timestamp" },
      { name: "expires_at", type: "TIMESTAMPTZ", constraints: "GENERATED ALWAYS AS (created_at + INTERVAL '24 hours') STORED", description: "Auto-destruct TTL" }
    ],
    sqlDdl: `-- Real-Time Screenshot & Recording Alert Logs
CREATE TABLE security_audit_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id UUID NOT NULL,
    reporter_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type VARCHAR(40) NOT NULL CHECK (event_type IN ('SCREENSHOT_DETECTED', 'SCREEN_RECORDING_DETECTED')),
    evidence_meta TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ GENERATED ALWAYS AS (created_at + INTERVAL '24 hours') STORED
);
CREATE INDEX idx_security_events_chat ON security_audit_events(chat_id, created_at);`,
    roomEntity: `// Android Room Entity for In-Chat Security Warning Indicators
@Entity(tableName = "chat_security_alerts")
data class ChatSecurityAlertEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "chat_id") val chatId: String,
    @ColumnInfo(name = "alert_type") val alertType: String,
    @ColumnInfo(name = "timestamp") val timestamp: Long,
    @ColumnInfo(name = "expires_at") val expiresAt: Long
)`
  },
  {
    name: "device_keys (X3DH / Signal Protocol)",
    description: "Public cryptographic identity and prekey bundles uploaded by clients for Double Ratchet key exchanges.",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "Key registration record ID" },
      { name: "user_id", type: "UUID", constraints: "REFERENCES users(id) ON DELETE CASCADE", description: "Owning user reference" },
      { name: "device_id", type: "VARCHAR(64)", constraints: "NOT NULL", description: "Unique client device installation ID" },
      { name: "identity_key_pub", type: "TEXT", constraints: "NOT NULL", description: "Base64 Curve25519 Identity Public Key (IK)" },
      { name: "signed_prekey_pub", type: "TEXT", constraints: "NOT NULL", description: "Base64 Curve25519 Signed Prekey (SPK)" },
      { name: "signed_prekey_sig", type: "TEXT", constraints: "NOT NULL", description: "Ed25519 Signature over SPK by IK" },
      { name: "registration_id", type: "INTEGER", constraints: "NOT NULL", description: "Signal protocol client registration ID" },
      { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Key upload timestamp" }
    ],
    sqlDdl: `CREATE TABLE device_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(64) NOT NULL,
    identity_key_pub TEXT NOT NULL,
    signed_prekey_pub TEXT NOT NULL,
    signed_prekey_sig TEXT NOT NULL,
    registration_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, device_id)
);`,
    roomEntity: `// Android Room Entity (Local Cryptographic Vault)
@Entity(tableName = "crypto_keys")
data class CryptoKeyEntity(
    @PrimaryKey val deviceId: String,
    @ColumnInfo(name = "identity_private_key_alias") val idKeyAlias: String, // Stored in Android Keystore
    @ColumnInfo(name = "identity_public_key") val idKeyPub: ByteArray,
    @ColumnInfo(name = "signed_prekey_id") val signedPrekeyId: Int,
    @ColumnInfo(name = "signed_prekey_pub") val signedPrekeyPub: ByteArray,
    @ColumnInfo(name = "created_at") val createdAt: Long
)`
  },
  {
    name: "ephemeral_messages",
    description: "Undelivered or transient encrypted message queue with strict 24-hour auto-destruct TTL constraint.",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "Message delivery envelope UUID" },
      { name: "chat_id", type: "UUID", constraints: "NOT NULL", description: "Conversation room ID" },
      { name: "sender_id", type: "UUID", constraints: "REFERENCES users(id)", description: "Sender User UUID" },
      { name: "recipient_id", type: "UUID", constraints: "REFERENCES users(id)", description: "Recipient User UUID" },
      { name: "encrypted_payload", type: "BYTEA", constraints: "NOT NULL", description: "Opaque ciphertext from Double Ratchet" },
      { name: "ephemeral_dh_pub", type: "TEXT", constraints: "NOT NULL", description: "Sender ratchet public key for this message" },
      { name: "ratchet_counter", type: "INTEGER", constraints: "NOT NULL", description: "Sequence number in current ratchet chain" },
      { name: "sent_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW() NOT NULL", description: "Message transmission time" },
      { name: "expires_at", type: "TIMESTAMPTZ", constraints: "GENERATED ALWAYS AS (sent_at + INTERVAL '24 HOURS') STORED", description: "Strict 24H hard cutoff timestamp" }
    ],
    sqlDdl: `CREATE TABLE ephemeral_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id UUID NOT NULL,
    sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    encrypted_payload BYTEA NOT NULL,
    ephemeral_dh_pub TEXT NOT NULL,
    ratchet_counter INTEGER NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMPTZ GENERATED ALWAYS AS (sent_at + INTERVAL '24 hours') STORED
);

-- Compound index for fast queue retrieval & rapid TTL pruning
CREATE INDEX idx_ephemeral_queue ON ephemeral_messages(recipient_id, sent_at);
CREATE INDEX idx_ephemeral_ttl ON ephemeral_messages(expires_at);`,
    roomEntity: `// Android Room Entity with 24H local self-destruct logic
@Entity(
    tableName = "local_messages",
    indices = [Index(value = ["expires_at"]), Index(value = ["chat_id"])]
)
data class LocalMessageEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "chat_id") val chatId: String,
    @ColumnInfo(name = "sender_id") val senderId: String,
    @ColumnInfo(name = "plaintext_cached") val decryptedText: String?, // Wiped at expiry
    @ColumnInfo(name = "attachment_id") val attachmentId: String?,
    @ColumnInfo(name = "sent_at") val sentAt: Long,
    @ColumnInfo(name = "expires_at") val expiresAt: Long // sentAt + 86,400,000 ms
)`
  },
  {
    name: "media_attachments (500 MB Chunked)",
    description: "Metadata and multi-part upload tracking for client-side encrypted media files.",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "File descriptor UUID" },
      { name: "s3_object_key", type: "VARCHAR(255)", constraints: "UNIQUE NOT NULL", description: "Unique cloud storage object key" },
      { name: "encrypted_file_size", type: "BIGINT", constraints: "NOT NULL", description: "Ciphertext size in bytes (max 524,288,000)" },
      { name: "total_chunks", type: "INTEGER", constraints: "NOT NULL", description: "Count of 5-10 MB chunks" },
      { name: "sha256_checksum", type: "VARCHAR(64)", constraints: "NOT NULL", description: "SHA-256 checksum of encrypted blob" },
      { name: "status", type: "VARCHAR(20)", constraints: "DEFAULT 'UPLOADING'", description: "UPLOADING, COMPLETED, EXPIRED" },
      { name: "uploaded_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Upload completion time" },
      { name: "expires_at", type: "TIMESTAMPTZ", constraints: "NOT NULL", description: "Calculated S3 Lifecycle match (24h)" }
    ],
    sqlDdl: `CREATE TABLE media_attachments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    s3_object_key VARCHAR(255) UNIQUE NOT NULL,
    encrypted_file_size BIGINT NOT NULL CHECK (encrypted_file_size <= 524288000), -- 500 MB Limit
    total_chunks INTEGER NOT NULL,
    sha256_checksum VARCHAR(64) NOT NULL,
    status VARCHAR(20) DEFAULT 'UPLOADING' CHECK (status IN ('UPLOADING', 'COMPLETED', 'EXPIRED')),
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_media_expires ON media_attachments(expires_at);`,
    roomEntity: `// Android Room Entity for Chunked Local File Cache
@Entity(tableName = "local_media_cache")
data class LocalMediaCacheEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "local_file_path") val localPath: String,
    @ColumnInfo(name = "mime_type") val mimeType: String,
    @ColumnInfo(name = "file_size_bytes") val sizeBytes: Long,
    @ColumnInfo(name = "is_fully_downloaded") val isDownloaded: Boolean,
    @ColumnInfo(name = "download_progress") val progressPercent: Int,
    @ColumnInfo(name = "expires_at") val expiresAt: Long
)`
  },
  {
    name: "call_sessions (WebRTC Audio/Video)",
    description: "P2P WebRTC session logs and metadata (ephemeral, zero recordings stored).",
    columns: [
      { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()", description: "Call session UUID" },
      { name: "caller_id", type: "UUID", constraints: "REFERENCES users(id)", description: "Initiator user ID" },
      { name: "callee_id", type: "UUID", constraints: "REFERENCES users(id)", description: "Recipient user ID" },
      { name: "call_type", type: "VARCHAR(10)", constraints: "CHECK (call_type IN ('AUDIO', 'VIDEO'))", description: "Call media mode" },
      { name: "status", type: "VARCHAR(20)", constraints: "CHECK (status IN ('RINGING', 'CONNECTED', 'ENDED', 'MISSED', 'REJECTED'))", description: "Lifecycle state" },
      { name: "started_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()", description: "Session start" },
      { name: "ended_at", type: "TIMESTAMPTZ", constraints: "NULL", description: "Session conclusion" },
      { name: "duration_seconds", type: "INTEGER", constraints: "DEFAULT 0", description: "Call duration" },
      { name: "expires_at", type: "TIMESTAMPTZ", constraints: "GENERATED ALWAYS AS (started_at + INTERVAL '24 hours') STORED", description: "Call log auto-destruct time" }
    ],
    sqlDdl: `CREATE TABLE call_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    caller_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    callee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    call_type VARCHAR(10) NOT NULL CHECK (call_type IN ('AUDIO', 'VIDEO')),
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    duration_seconds INTEGER DEFAULT 0,
    expires_at TIMESTAMPTZ GENERATED ALWAYS AS (started_at + INTERVAL '24 hours') STORED
);
CREATE INDEX idx_call_expires ON call_sessions(expires_at);`,
    roomEntity: `// Android Room Entity for Ephemeral Call History
@Entity(tableName = "local_call_logs")
data class LocalCallLogEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "peer_id") val peerId: String,
    @ColumnInfo(name = "peer_name") val peerName: String,
    @ColumnInfo(name = "call_type") val callType: String, // "AUDIO" | "VIDEO"
    @ColumnInfo(name = "direction") val direction: String, // "INCOMING" | "OUTGOING"
    @ColumnInfo(name = "duration_seconds") val durationSeconds: Int,
    @ColumnInfo(name = "timestamp") val timestamp: Long,
    @ColumnInfo(name = "expires_at") val expiresAt: Long
)`
  }
];

export const ROADMAP_PHASES: RoadmapPhase[] = [
  {
    phase: "Phase 1",
    title: "Cryptographic Core & Identity Foundation",
    duration: "Weeks 1 - 3",
    focus: "Establish Google OAuth, Android Keystore bindings, and Signal Protocol / Double Ratchet cryptographic engine.",
    milestones: [
      "Configure Firebase Authentication with Google Sign-In & JWT token exchange on backend gateway.",
      "Implement Android Keystore module to generate and protect Curve25519 Identity Keypairs.",
      "Develop X3DH key registration API (Identity Key, Signed Prekey, and pool of One-Time Prekeys).",
      "Validate Double Ratchet state transitions, forward secrecy, and break-in recovery with comprehensive unit tests."
    ],
    deliverables: [
      "Secure Login flow with auto-session refresh",
      "Cryptographic Engine Module (libsignal or libsodium FFI wrapper)",
      "Device registration & Public Prekey bundle publishing pipeline"
    ]
  },
  {
    phase: "Phase 2",
    title: "Real-time Messaging & 24H Auto-Destruct Engine",
    duration: "Weeks 4 - 6",
    focus: "Real-time WebSocket signaling, 1-on-1 encrypted chat, local Room database with SQLCipher, and 24-hour TTL deletion.",
    milestones: [
      "Deploy Go/Fastify WebSocket signaling gateway with Redis Pub/Sub horizontal routing.",
      "Build Android Jetpack Room encrypted database with SQLCipher integration.",
      "Implement Android WorkManager periodic job running every 15 minutes to delete messages where System.currentTimeMillis() > expiresAt.",
      "Implement backend PostgreSQL pg_cron / scheduled Cloud Run worker purging expired rows every 5 minutes."
    ],
    deliverables: [
      "1-on-1 real-time E2EE messaging with delivery receipts (Sent, Delivered, Read)",
      "Self-destruct timer UI indicator with second-by-second countdown",
      "Automated background disk sanitation on mobile and server"
    ]
  },
  {
    phase: "Phase 3",
    title: "500 MB Encrypted Chunked File Transfer System",
    duration: "Weeks 7 - 9",
    focus: "Client-side AES-256-GCM chunked file encryption, S3 multi-part presigned upload flow, and background resumable transfers.",
    milestones: [
      "Create client streaming file slicer: partition 500 MB files into 10 MB chunks with individual IVs and HMAC tags.",
      "Implement backend AWS S3 presigned URL multi-part generation endpoint.",
      "Build OkHttp concurrent chunk uploader with progress tracking Flow and pause/resume capability.",
      "Configure AWS S3 Bucket Lifecycle Policy to automatically purge objects after 24 hours."
    ],
    deliverables: [
      "Support for media/documents up to 500 MB with live percentage & MB/s transfer speed",
      "Zero-knowledge server pipeline: server never receives encryption keys or plaintext files",
      "Instant media thumbnail previews generated locally before encryption"
    ]
  },
  {
    phase: "Phase 4",
    title: "WebRTC 1-on-1 Voice & Video Calling",
    duration: "Weeks 10 - 12",
    focus: "Native WebRTC peer-to-peer audio and video engine with DTLS-SRTP encryption and COTURN relay fallback.",
    milestones: [
      "Deploy COTURN servers with time-limited ephemeral credentials across multi-region cloud nodes.",
      "Implement WebRTC signaling state machine over WebSocket (Offer, Answer, ICE Candidate exchange).",
      "Configure audio processing (AEC acoustic echo cancellation, AGC automatic gain control, NS noise suppression).",
      "Build modern calling UI with camera flip, mute, speaker toggle, and picture-in-picture (PiP) support."
    ],
    deliverables: [
      "Crystal-clear 1-on-1 Voice calls using Opus codec (up to 48kHz HD audio)",
      "Adaptive HD 1080p Video calls with automated network downgrade (VP8/VP9)",
      "Direct P2P connectivity with under 150ms round-trip latency"
    ]
  },
  {
    phase: "Phase 5",
    title: "Hardening, Security Audits & Production MVP Release",
    duration: "Weeks 13 - 14",
    focus: "Penetration testing, memory zeroization, crash reporting, and Google Play Store deployment.",
    milestones: [
      "Audit memory zeroization: ensure all byte arrays holding symmetric keys are immediately overwritten with zeros after use.",
      "Enforce Android FLAG_SECURE to prevent screenshots and screen recording in secure chats.",
      "Configure Firebase App Check and Google Cloud Armor for rate limiting and DDoS mitigation.",
      "Beta deployment via Google Play Internal Testing track with automated crash telemetry."
    ],
    deliverables: [
      "Independent cryptographic & zero-knowledge security audit report",
      "Production-ready signed Android APK / App Bundle",
      "Complete operational monitoring dashboard (Datadog/Grafana + Sentry)"
    ]
  }
];
